model_params:
  model: ContainersModel
  encoder_name: "efficientnet_b1"
  num_classes: 3
  pretrained: True
  dropout_rate: 0.8

args:
  expdir: src
  baselogdir: logs
  verbose: True

stages:
  data_params:
    batch_size: 32
    num_workers: 4
    path_to_dataframe: ./data/processed/train/data.csv
    fold: 0

  criterion_params:
    criterion: FocalLossMultiClass

  optimizer_params:
    optimizer: AdamW
    lr: 0.0001
    weight_decay: 0.0

  scheduler_params:
    scheduler: ReduceLROnPlateau
    mode: max
    patience: 5
    factor: 0.75
    verbose: False

  state_params:
    main_metric: accuracy01
    minimize_metric: False

  stage1:
    stage_params:
      num_epochs: 100

    callbacks_params:
      loss:
        callback: CriterionCallback

      optimizer:
        callback: OptimizerCallback

      scheduler:
        callback: SchedulerCallback

      accuracy:
        callback: AccuracyCallback

      f1score:
        callback: F1ScoreCallback

      precision:
        callback: PrecisionCallback

      recall:
        callback: RecallCallback

      wandb:
        callback: WandbLogger
        metric_names: [ "accuracy01", "recall", "precision", "f1score", "loss" ]
        log_on_epoch_end: True

      tracer:
        callback: TracerCallback
        metric: accuracy01
        minimize: False
        mode: best
